[tox]
envlist =
    py39-django{42}
    py310-django{50, 51, 52}
    py311-django{50, 51, 52}
    py312-django{50, 51, 52}
    py313-django{51, 52}

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/djangorestframework-camel-case
commands =
    python \
      -W error::ResourceWarning \
      -W error::DeprecationWarning \
      -W error::PendingDeprecationWarning \
      tests.py
deps =
    -r{toxinidir}/requirements.txt
    setuptools
    django42: Django>=4.2a1,<5.0
    django50: Django>=5.0a1,<5.1
    django51: Django>=5.1a1,<5.2
    django52: Django>=5.2a1,<6.0
